env:
  DOCKER_BUILDKIT: 1
  REGISTRY: "registry.agilepromoter.com"
  ECR_REGISTRY: "372153259551.dkr.ecr.us-east-1.amazonaws.com/"

steps:
  - label: "Debian"
    key: "debian"
    env:
      BASE_IMAGE: "debian:stable-slim"
      IMAGE_NAME: "base-debian"
    command:
      - docker build --pull --no-cache --tag $$REGISTRY/$$IMAGE_NAME --build-arg BASE_IMAGE=$$BASE_IMAGE .
      - docker push $$REGISTRY/$$IMAGE_NAME
    agents:
      queue: "docker"

  - label: "Node 14"
    key: "node14"
    env:
      BASE_IMAGE: "node:14-slim"
      IMAGE_NAME: "base-node14"
    command:
      - docker build --pull --no-cache --tag $$REGISTRY/$$IMAGE_NAME --build-arg BASE_IMAGE=$$BASE_IMAGE .
      - docker push $$REGISTRY/$$IMAGE_NAME
    agents:
      queue: "docker"

  - label: "Node 16"
    key: "node16"
    env:
      BASE_IMAGE: "node:16-slim"
      IMAGE_NAME: "base-node16"
    command:
      - docker build --pull --no-cache --tag $$REGISTRY/$$IMAGE_NAME --build-arg BASE_IMAGE=$$BASE_IMAGE .
      - docker push $$REGISTRY/$$IMAGE_NAME
    agents:
      queue: "docker"

  - label: "Node 16 ECR"
    key: "node16"
    env:
      BASE_IMAGE: "node:16-slim"
      IMAGE_NAME: "base-node16"
    command:
      - docker build --pull --no-cache --tag $$ECR_REGISTRY/$$IMAGE_NAME --build-arg BASE_IMAGE=$$BASE_IMAGE .
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 372153259551.dkr.ecr.us-east-1.amazonaws.com
      - docker push $$ECR_REGISTRY/$$IMAGE_NAME
    agents:
      queue: "dockerecr"